### ISSUE TITLE
please make new release

### ISSUE THREAD

**Issue by ygrek** [xavierleroy/camlidl#16]
ref https://github.com/ocaml/opam-repository/pull/16179

**Comment by xavierleroy** [comment]
Here you are: https://github.com/xavierleroy/camlidl/releases/tag/camlidl108

**Comment by xavierleroy** [comment]
Something was questionable in release 1.08.  Better use https://github.com/xavierleroy/camlidl/releases/tag/camlidl109 .

**Comment by ygrek** [comment]
Thanks.
https://github.com/ocaml/opam-repository/pull/16593
