### ISSUE TITLE
How to build manual/docs?

### ISSUE THREAD

**Issue by dboris** [xavierleroy/camlidl#20]
The `doc` directory contains the etex source of the manual, but no PDF or html version as implied in the README. The Makefile refers to packages which are not available on my system. What are the requirements to make the docs? Would it be possible to include a PDF version in the repo?

**Comment by xavierleroy** [comment]
The PDF manual should build again in release 1.10.  The HTML manual was also made available at https://xavierleroy.org/camlidl/
