### ISSUE TITLE
Build against ocaml-4.06 and ocaml-4.07 fails

### ISSUE THREAD

**Issue by jakoblichtenberg** [xavierleroy/camlidl#6]
I am trying to move my OCaml toolset forward.  

Question: Has anyone been able to build CamlIDL with OCaml 4.06.1 or 4.07.0?

For what it is worth here are my experiences.  

Two separate problems:

1: In order to move from OCaml 4.05 to OCaml 4.06 I had to apply following hack:
--- runtime/cfactory.cpp        2017-11-25 08:45:50.000000000 -0800
+++ runtime/cfactory_new.cpp    2018-09-05 20:35:21.186703000 -0700
@@ -195,7 +195,7 @@
     dup2(fd, 2);
     close(fd);
 #endif
-    caml_startup(argv);
+    caml_startup((char_os **) argv);
     break;
   /* TODO: free all memory when DLL detached */
   }

2. In order to additionally move to 4.07 I got some issue related to Stdlib.  Probably due to change https://github.com/ocaml/ocaml/pull/1010 .  

Best regards and thank you.

**Comment by jakoblichtenberg** [comment]
Update: 

I was able to move my OCaml toolset forward to 4.07 together with CamlIDL 1.06.

1. The cfactory_new.cpp compile issue continued to be an issue.  So I applied patch above as a 'workaround' and I have not encountered any problems yet.  

2. The issue regarding Stdlib evaporated.  I am not exactly sure why I hit this two days ago, but not again.

Thank you!

**Comment by ygrek** [comment]
use ``` to separate code blocks, your patch above is unreadable. Also please show what error you get in first place. camlidl compiles cleanly on 4.06 and 4.07 for me

**Comment by xavierleroy** [comment]
@ygrek: I think the issue is in Windows-specific code, so if you're not under Windows you didn't see it.

**Comment by xavierleroy** [comment]
I pushed a tentative fix to the master branch, but I haven't tested it and may not be able to do so anytime soon.  Anyone with a working Windows development environment is welcome to test and report here.

**Comment by jakoblichtenberg** [comment]
I got a fresh Windows environment.  Will test and report back. Thank you!

On Sep 23, 2018, at 18:52, Xavier Leroy <notifications@github.com<mailto:notifications@github.com>> wrote:


I pushed a tentative fix to the master branch, but I haven't tested it and may not be able to do so anytime soon. Anyone with a working Windows development environment is welcome to test and report here.

**Comment by yakobowski** [comment]
@xavierleroy I have successfully built CamlIdl under Cygwin+Mingw. Not sure whether you meant that port, or a full MSVC build.

**Comment by jakoblichtenberg** [comment]
@xavierleroy .  Just want to report back that I validated fix and it works well.  Here is my configuration: Visual Studio 2019 Build Tools, ocaml-4.08.0+beta3, FlexDLL 0.37. cygwin used to build with native VS tools.  Thank you.  Jakob

PS. In validation process I discovered an issue related to move from ocaml-4.07.0 to ocaml-4.08.0+beta3.  I will report this separately.

**Comment by jakoblichtenberg** [comment]
I believe this issue can be closed out.

**Comment by xavierleroy** [comment]
Thank you for the confirmation.
