### ISSUE TITLE
LICENSE still refers to Q Public License, but OCaml is under LGPL 2.1 now

### ISSUE THREAD

**Issue by greg-kennedy** [xavierleroy/camlidl#7]
File `LICENSE` in the root has the Q Public License text and says that things from INRIA are under QPL... however, since April 2016 (OCaml release 4.03) the INRIA sources should be LGPL 2.1.

It would be nice to update the LICENSE file... In fact, if camlidl could also be updated to 2.1, they could share the exact same LICENSE instead.

**Comment by xavierleroy** [comment]
I'm not sure what you mean by "the INRIA sources should be LGPL 2.1".  Each project chooses its license(s).  Nothing is broken as a consequence of the "compiler" part of CamlIDL still being under the QPL while the "compiler" part of OCaml moved to LGPL 2.1.

If you mean that it would make sense to switch CamlIDL to LGPL 2.1 for the same reasons OCaml switched to LGPL 2.1, I globally agree, but need to find time to make the change.

**Comment by greg-kennedy** [comment]
Sorry, I misunderstood - I thought the license was saying that CamlIDL included code from OCaml which was under QPL.  Since OCaml had updated their license, it should be reflected here.

But that's not what it meant, I misread :)

**Comment by xavierleroy** [comment]
Commit 5ce4c63 changes the license of the CamlIDL compiler to LGPL 2.1, as previously discussed.
