### ISSUE TITLE
linking against libcamlidl is complicated

### ISSUE THREAD

**Issue by ygrek** [xavierleroy/camlidl#8]
Currently one needs to pass -lcamlidl manually when including camlidl generated code into project, which can be quite [non-obvious](https://github.com/ygrek/ocaml-hdfs/commit/1c6ad6805318a975ace9b6396ed69b255b08dd51#diff-2d8a8d7d55d223fe187efdf03f6ca050R902) to achieve with modern build systems. It would be much simpler if `-package camlidl` did that automatically. The patch below achieves the effect, and I believe ocaml compiler drops com.cmxa from final binary when it is not referenced so there is no extra cost. This might cause problems on windows where it can be even more cumbersome to link against distributed C libraries, so the other option would be to have separate ocamlfind package with empty cma only for the purpose of embedding -cclib.

```
diff --git a/lib/Makefile b/lib/Makefile
index c544b5e..aa0c47d 100644
--- a/lib/Makefile
+++ b/lib/Makefile
@@ -23,10 +23,10 @@ INTERFACES=$(BYTEOBJS:.cmo=.cmi)
 all: $(BYTELIB) $(NATIVELIB)
 
 $(BYTELIB): $(BYTEOBJS)
-       $(OCAMLC) -a -o $(BYTELIB) $(BYTEOBJS)
+       $(OCAMLC) -a -o $(BYTELIB) -cclib -lcamlidl $(BYTEOBJS)
 
 $(NATIVELIB): $(NATIVEOBJS)
-       $(OCAMLOPT) -a -o $(NATIVELIB) $(NATIVEOBJS)
+       $(OCAMLOPT) -a -o $(NATIVELIB) -cclib -lcamlidl $(NATIVEOBJS)
 
 install:
        cp $(INTERFACES) $(BYTELIB) $(NATIVELIB) $(NATIVELIB:.cmxa=.$(LIBEXT)) $(OCAMLLIB)
```

**Comment by ygrek** [comment]
ping

**Comment by xavierleroy** [comment]
Sorry for leaving this issue open for so long.  I agree with the proposed solution.  For bytecode we can have `-dllib -lcamlidl` in addition, so that the DLL can be automatically used too.  It's in commit  d8f7a3f .  I do hope there will be no issues with double linking of `-lcamlidl`.
